main yml added

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,12 +6,29 @@ on:
       - master
 
 jobs:
-  deploy:
+  deploy_to_server_1:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
+
+      - name: Cache npm modules
+        uses: actions/cache@v2
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-
+
+      - name: Install npm dependencies
+        run: npm ci
+
+      # Step to check if npm build is required
+      - name: Check if npm build is required
+        id: build-check
+        run: |
+          git diff --quiet HEAD^ HEAD -- resources/ || echo "build_required=true" >> $GITHUB_ENV
 
       - name: Deploy to server 1 via SSH
         uses: appleboy/ssh-action@v1.0.3
@@ -30,6 +47,30 @@ jobs:
             php artisan route:cache
             npm install
             npm run build
+
+  deploy_to_server_2:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Cache npm modules
+        uses: actions/cache@v2
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-
+
+      - name: Install npm dependencies
+        run: npm ci
+
+      # Step to check if npm build is required
+      - name: Check if npm build is required
+        id: build-check
+        run: |
+          git diff --quiet HEAD^ HEAD -- resources/ || echo "build_required=true" >> $GITHUB_ENV
 
       - name: Deploy to server 2 via SSH
         uses: appleboy/ssh-action@v1.0.3
